//
// Created by bruh on 1/8/16.
//

#ifndef ROBOY_CONTROL_COMMONDEFINITIONS_H
#define ROBOY_CONTROL_COMMONDEFINITIONS_H

enum ControlMode {POSITION_CONTROL, FORCE_CONTROL};
enum ControllerState {UNDEFINED, INITIALIZED, TRAJECTORY_READY, PLAYING};

#endif //ROBOY_CONTROL_COMMONDEFINITIONS_H
